---
- name: Run ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Run starship tasks
  ansible.builtin.include_tasks: starship.yaml

- name: "Git clone zsh plugins"  # noqa: latest[git]
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ zsh_root }}/plugins/{{ item.name }}"
  loop: "{{ zsh_plugins }}"
  loop_control:
    label: "{{ item.name }}"

- name: Setup .zshrc template
  ansible.builtin.template:
    src: .zshrc.j2
    dest: ~/.zshrc
    mode: '0644'
