---
- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    update_cache: true
    state: present
  become: true

- name: Ensure zsh is the default shell for invoking user
  ansible.builtin.user:
    name: "{{ ansible_facts.env.SUDO_USER | default(ansible_env.USER) }}"
    shell: /bin/zsh
  become: true
  when: ansible_facts.user_shell != "/bin/zsh"
