---
- name: Run ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Run macos specific tasks
  ansible.builtin.include_tasks: macos.yaml
  when: ansible_facts['distribution'] == 'MacOSX'

- name: Run mise tools installation tasks
  ansible.builtin.include_tasks: tools.yaml

- name: "Set mise trusted_config_paths"
  ansible.builtin.command: "mise settings set trusted_config_paths {{ mise_trusted_config_paths | to_json }}"
  changed_when: false
