- name: "Mise use -g {{ item }}"  # noqa: latest[command-instead-of-shell]
  ansible.builtin.command: "mise use -g {{ item }}"
  args:
    creates: "{{ ansible_facts.env.HOME }}/.local/share/mise/installs/{{ item.split('@')[0] }}/{{ item.split('@')[1] }}"
  loop: "{{ mise_tools }}"
