- name: Ensure required APT keyring directory exists
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download Cloudflare GPG key
  ansible.builtin.get_url:
    url: https://pkg.cloudflare.com/cloudflare-main.gpg
    dest: /usr/share/keyrings/cloudflare-main.gpg
    mode: '0644'
    force: true
  become: true

- name: Add Cloudflared APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared {{ ansible_distribution_release | lower }} main"
    filename: cloudflared
    state: present
    update_cache: true
  become: true

- name: Install cloudflared
  ansible.builtin.apt:
    name: cloudflared
    state: present
  become: true
